# Configuration file for SCVURv2 Part 1

# Author: Teresita M. Porter
# Date: Oct. 21, 2019

############################################################################
# General pipeline settings
############################################################################

# Number of cores available to run pipeline taken from command line
# snakemake --jobs 10
#jobs: "10"

############################################################################
# Identify raw read files
############################################################################

# This directory contains raw reads (all of them or from just one run)
# Only use compressed fastq files with this pipeline, ex. fastq.gz
# For the alternate pipeline, call the directory "run1", "run2", etc.
raw: "run1"

# Indicate 'sample' and 'read' wildcards in raw filenames:
# These files should be in a "run2" or "run2", etc. folder
# Sample filename structure,
# 	SITE-CONDITION-REPLICATE_S1_L001_R1_001.fastq.gz
# 	{sample}_L001_R{read}_001.fastq.gz
raw_sample_read_wildcards: "run1/{sample}_L001_R{read}_001.fastq.gz"

# SEQPREP sample wildcard and parameters
# These files should be in a "run2" or "run2", etc. folder
# Sample,
#	{sample}_L001_R1_001.fastq.gz
raw_sample_forward_wildcard: "run1/{sample}_L001_R1_001.fastq.gz"
raw_sample_reverse_wildcard: "run1/{sample}_L001_R2_001.fastq.gz"

############################################################################
# Raw read pairing
############################################################################

SEQPREP:
# Phred score quality cutoff
    q: 20
# Minimum overlap length between forward and reverse reads
    o: 25

############################################################################
# Primer trimming
############################################################################

# CUTADAPT parameters
CUTADAPT_FWD:
    g: "GTGYCAGCMGCCGCGGTAA"
    m: 150
    q: "20,20"
    mn: 3

CUTADAPT_REV:
    a: "AAACTYAAAKRAATTGRCGG"
    m: 150
    q: "20,20"
    mn: 3


############################################################################
# Dereplication
############################################################################

# Indicate a directory name here that is short and simple with no spaces or weird punctuation
# For the alternate pipeline, a good directory name would be the run number, ex. "run1_out"
dir: "run1_out"

# VSEARCH params
VSEARCH:
# Indicate number of threads to use
# Do not exceed the number of jobs allotted to run the whole pipeline ('jobs' above)
    t: 24


############################################################################
# Denoising
############################################################################

# Indicate minimum number of reads per cluster to retain
# Here, remove all singletons and doubletons, retain clusters with 3+ reads

USEARCH:
    minsize: 3


